import CreateForm from "./CreateForm";

export const metadata = {
  title: "Dojo Helpdesk | Create Ticket",
  description: "Generated by create next app",
};

export default function CreateTicket() {
  return (
    <main>
        <h2 className="text-primary text-center">Add a new Ticket</h2>
        <CreateForm />
    </main>
  )
}
